# Registro de plugins que el microkernel cargara dinamicamente via Reflexion.
# clave=nombre.completo.de.la.Clase
plugin.1=co.unicauca.saberpro.microkernel.plugins.MultipleChoiceQuestionPlugin
plugin.2=co.unicauca.saberpro.microkernel.plugins.CaseQuestionPlugin
plugin.3=co.unicauca.saberpro.microkernel.plugins.MultimediaQuestionPlugin
